name: 'Kiuwan Delivery Analysis'
author: 'Kiuwan'
description: 'Run Kiuwan Delivery Analysis on the selected set of code'
inputs:
  project:
    description: 'Name of Kiuwan project'
    required: false
    default: ${{ github.repository }}
  label:
    description: 'Label of the analysis'
    required: false
    default: ${{ github.run_number }}
  userid:
    description: 'Username for kiuwan platform'
    required: true
  password:
    description: 'Password for kiuwan platform'
    required: true
  changerequest:
    description: 'Change request for the delivery analysis'
    required: false
  branch:
    description: 'Branch name for the delivery analysis'
    requrired: false
  type:
    description: 'Type of delivery: completeDelivery(default) or partialDelivery'
    required: false
    default: 'completeDelivery'
  status:
    description: 'Status of the delivery: resolved(default) or inprogress'
    required: false
    default: 'resolved'
  includepatterns:
    description: 'List of comma separated folder expressions to include in the analysis. Example: **/test/**'
    required: false
  excludepatterns:
    description: 'List of comma separated folder expressions to exclude from the analisis. Example: **/test/**'
    required: false
  databasetype:
    description: 'Database type files in the project, if any. Can be one of [none, transacsql, plsql, informix]'
    required: false
    default: 'none'
  maxmemory:
    description: 'maximum memory allocated for java virtual machine heap, in megabytes. Example: 2048'
    required: false
    default: '1024'
  timeout:
    description: 'maximum time (in minutes) that the analysis is going to run before stopping.'
    required: false
    default: '60' 
    
outputs:
  result:
    description: 'Return code of the execution of kiuwan'
  analysisurl:
    description: 'URL of the executed analysis'    
  auditresult:
    description: 'Result of the audit to check [ok | fail]'
    
branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'docker'
  image: 'Dockerfile'
  
